#!/usr/bin/env python3

from argparse import ArgumentParser
from qt_create import create_qt_ros_catkin_package


def main():
    parser = ArgumentParser(usage="usage: %prog <package-name> [dependencies...]")
    parser.add_argument("package_name", help="The name of the package to create")
    parser.add_argument("dependencies", nargs="*", help="The names of the packages that this package depends on")
    args = parser.parse_args()

    # Check that the package name is valid.
    if not args.package_name:
        parser.error("You must specify a package name.")

    # Check that the dependencies are valid.
    for dependency in args.dependencies:
        if not dependency:
            parser.error("You must specify a dependency name.")

    # Create the package.
    create_qt_ros_catkin_package(args.package_name, args.dependencies)
    print("\nPlease edit {}/package.xml and mainpage.dox to finish creating your package".format(args.package_name))


if __name__ == "__main__":
    main()
